FROM php:8.2-apache


# Enable Apache mod_rewrite
RUN a2enmod rewrite


# Install necessary PHP extensions
RUN docker-php-ext-install pdo pdo_mysql mysqli


# Copy project files
COPY . /var/www/html/


# Set correct permissions
RUN chown -R www-data:www-data /var/www/html


# Set working directory
WORKDIR /var/www/html


# Expose port 80
EXPOSE 80
