services:
  - type: web
    name: codeigniter-app
    env: docker
    repo: https://github.com/SHUFFYCODE/student_management_system
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: APP_BASEURL
        value: https://codeigniter-app.onrender.com/


