services:
  - type: web
    name: student-management-system
    env: docker
    plan: free
    repo: https://github.com/SHUFFYCODE/student_management_system
    branch: main
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    autodeploy: true